id: meta-llama/Llama-3.1-8B-Instruct
name: Llama-3.1-8B-Instruct
namespace: meta-llama
aliases:
  - Meta-Llama-3.1-8B-Instruct
reference_links:
  - name: Hugging Face
    url: https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct
