id: bbq
name: bbq
tags:
  - social_bias
metrics:
  - acc
  - accuracy_amb
  - accuracy_disamb
  - amb_bias_score
  - disamb_bias_score
  - amb_bias_score_Age
  - amb_bias_score_Disability_status
  - amb_bias_score_Gender_identity
  - amb_bias_score_Nationality
  - amb_bias_score_Physical_appearance
  - amb_bias_score_Race_ethnicity
  - amb_bias_score_Race_x_gender
  - amb_bias_score_Race_x_SES
  - amb_bias_score_Religion
  - amb_bias_score_SES
  - amb_bias_score_Sexual_orientation
  - disamb_bias_score_Age
  - disamb_bias_score_Disability_status
  - disamb_bias_score_Gender_identity
  - disamb_bias_score_Nationality
  - disamb_bias_score_Physical_appearance
  - disamb_bias_score_Race_ethnicity
  - disamb_bias_score_Race_x_gender
  - disamb_bias_score_Race_x_SES
  - disamb_bias_score_Religion
  - disamb_bias_score_SES
  - disamb_bias_score_Sexual_orientation
