id: crows_pairs_english_religion
name: CrowS-Pairs English Religion
description: CrowS-Pairs English Religion - measures religion-based stereotype bias in masked language models for English language
tags:
  - bias
  - stereotyping
  - fairness
  - religion
category: language_modeling
languages:
  - en
