id: crows_pairs_english_autre
name: CrowS-Pairs English Other
description: CrowS-Pairs English Other - measures other stereotype bias in masked language models for English language
tags:
  - bias
  - stereotyping
  - fairness
  - other
category: language_modeling
languages:
  - en
