id: crows_pairs_english_disability
name: CrowS-Pairs English Disability
description: CrowS-Pairs English Disability - measures disability-based stereotype bias in masked language models for English language
tags:
  - bias
  - stereotyping
  - fairness
  - disability
category: language_modeling
languages:
  - en
