id: crows_pairs_french_race_color
name: CrowS-Pairs French Race/Color
description: CrowS-Pairs French Race/Color - measures race/color-based stereotype bias in masked language models for French language
tags:
  - bias
  - stereotyping
  - fairness
  - race
  - color
category: language_modeling
languages:
  - fr
