id: crows_pairs_english
name: crows_pairs_english
description: CrowS-Pairs - measures stereotype bias in masked language models
tags:
  - bias
  - stereotyping
  - fairness
category: language_modeling
languages:
  - en
