id: crows_pairs_french_physical_appearance
name: CrowS-Pairs French Physical Appearance
description: CrowS-Pairs French Physical Appearance - measures physical appearance-based stereotype bias in masked language models for French language
tags:
  - bias
  - stereotyping
  - fairness
  - physical_appearance
category: language_modeling
languages:
  - fr