id: winogender_male
name: Winogender Male
description: Winogender Male - measures gender bias in coreference resolution for male pronouns
tags:
  - winogender
  - gender
  - bias
  - social_bias
category: coreference_resolution
metrics:
  - acc
languages:
  - en
