id: winogender_neutral
name: Winogender Neutral
description: Winogender Neutral - measures gender bias in coreference resolution for neutral pronouns
tags:
  - winogender
  - gender
  - bias
  - social_bias
category: coreference_resolution
languages:
  - en
