id: winogender_gotcha
name: Winogender Gotcha
description: Winogender Gotcha - measures gender bias in coreference resolution with adversarial examples
tags:
  - winogender
  - gender
  - bias
  - social_bias
category: coreference_resolution
languages:
  - en
